swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions:
      get:
        security:
          - Bearer: []
        tags:
          - Transactions Module
        summary: Return every transactions of the month.
        description: API that get every transactions of the month.
        responses:
          "200":
            description: OK - Successfully recovered every transactions of the month
            schema:
              $ref: "#/definitions/TransactionsResponse"
          "400":
            description: Invalid Fields
          "404":
            description: Invalid transaction
          "500":
            description: Internal Server Error
  /transactions/{trId}:
      get:
        security:
          - Bearer: []
        tags:
          - Transactions Module
        summary: Return specific transaction.
        description: API that get a specific transaction.
        parameters:
          - in: path
            name: trId
            required: true
            type: string
            minimum: 1
            description: The ID of the transaction to return.
        responses:
          "200":
            description: Successfully recovered targeted transaction.
            schema:
              $ref: "#/definitions/SpecificTransactionResponse"
          "400":
            description: Invalid Fields
          "404":
            description: Invalid transaction
          "500":
            description: Internal Server Error
  /transactions/{trId}/{detail}:
      delete:
        security:
          - Bearer: []
        tags:
          - Transactions Module
        summary: Delete a note or a category of a specific transaction.
        description: API that delete a note or a category of a specific transaction.
        parameters:
          - in: path
            name: trId
            required: true
            type: string
            description: The ID of the transaction to modify.
          - in: path
            name: detail
            required: true
            type: string
            description: Specify whether to delete a note or a category.
        responses:
          "200":
            description: Successfully deleted.
          "400":
            description: Invalid Fields
          "404":
            description: Invalid transaction
          "500":
            description: Internal Server Error
      put:
        security:
          - Bearer: []
        tags:
          - Transactions Module
        summary: Update a note or a category of a specific transaction.
        description: API that update a note or a category of a specific transaction.
        parameters:
          - in: path
            name: trId
            required: true
            type: string
            description: The ID of the transaction to modify.
          - in: path
            name: detail
            required: true
            type: string
            description: Specify whether to update a note or a category.
          - in: body
            name: transactionUpdate
            required: transactionUpdate
            schema:
              $ref: "#/definitions/TransactionUpdate"
        responses:
          "200":
            description: Successfully updated.
          "400":
            description: Invalid Fields
          "404":
            description: Invalid transaction
          "500":
            description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transactions:
    type: object
    properties:
      id:
        type: string
        description: Transaction ID
      date:
        type: string
        format: date
        description: Transaction Date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: number
        description: Transaction balance
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        description: Response description
      body:
        type: array
        items:
          $ref: "#/definitions/Transactions" 
        description: Transaction's array
  SpecificTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        description: Response description
      type:
        type: string
      category:
        type: string
      note:
        type: string
  TransactionUpdate:
    type: object
    properties:
      status:
        type: integer
      trId:
          type: string
          description: The ID of the transaction to modify.
      detail:
          type: string
          description: Specify whether to update a note or a category.
      category:
          type: string
          description: Updated category.
      note:
          type: string
          description: Updated note.
